name: Manual Build Wheels (Testing)

on:
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version'
        required: true
        default: '3.11'
      os:
        description: 'Operating system'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest

jobs:
  build:
    runs-on: ${{ github.event.inputs.os }}
    name: Build wheel on ${{ github.event.inputs.os }} for Python ${{ github.event.inputs.python-version }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ github.event.inputs.python-version }}

      - name: Install cibuildwheel
        run: pip install cibuildwheel

      - name: Build wheels
        run: cibuildwheel --output-dir wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ github.event.inputs.os }}-py${{ github.event.inputs.python-version }}
          path: wheelhouse/*.whl

